/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex("attractions").del();
  await knex.raw("ALTER TABLE attractions AUTO_INCREMENT = 1");
  await knex("attractions").insert([
    // London (1-10)
    {
      location: "London",
      attraction_name: "Big Ben",
      description: "Iconic clock tower and landmark in London.",
      suggested_duration: "30min - 1hr",
      tags: "landmark,history,culture",
      image: "Photo-1.jpg",
    },
    {
      location: "London",
      attraction_name: "Tower of London",
      description: "Medieval castle and former prison.",
      suggested_duration: "1hr - 2hr",
      tags: "castle,history,leisure",
      image: "Photo-2.jpg",
    },
    {
      location: "London",
      attraction_name: "British Museum",
      description: "World-famous museum with historical artifacts.",
      suggested_duration: "1hr - 2hr",
      tags: "museum,culture,history",
      image: "Photo-3.jpg",
    },
    {
      location: "London",
      attraction_name: "London Eye",
      description: "Ferris wheel offering panoramic city views.",
      suggested_duration: "30min - 1hr",
      tags: "view,landmark,leisure",
      image: "Photo-4.jpg",
    },
    {
      location: "London",
      attraction_name: "Hyde Park",
      description: "Large city park with walking paths and a lake.",
      suggested_duration: "1hr - 3hr",
      tags: "park,nature,leisure",
      image: "Photo-5.jpg",
    },
    {
      location: "London",
      attraction_name: "Buckingham Palace",
      description: "Official residence of the British monarch.",
      suggested_duration: "1hr - 2hr",
      tags: "royal,landmark,history",
      image: "Photo-6.jpg",
    },
    {
      location: "London",
      attraction_name: "Tate Modern",
      description: "Modern art gallery housed in a former power station.",
      suggested_duration: "1hr - 2hr",
      tags: "museum,art,culture",
      image: "Photo-7.jpg",
    },
    {
      location: "London",
      attraction_name: "Covent Garden",
      description: "Vibrant area with markets, shops, and street performers.",
      suggested_duration: "1hr - 2hr",
      tags: "market,shopping,leisure",
      image: "Photo-8.jpg",
    },
    {
      location: "London",
      attraction_name: "St. Paul’s Cathedral",
      description: "Historic cathedral with a famous dome.",
      suggested_duration: "1hr - 2hr",
      tags: "church,landmark,architecture",
      image: "Photo-9.jpg",
    },
    {
      location: "London",
      attraction_name: "Camden Market",
      description: "Lively market known for food, fashion, and alternative culture.",
      suggested_duration: "1hr - 2hr",
      tags: "market,food,shopping",
      image: "Photo-10.jpg",
    },
    {
      location: "London",
      attraction_name: "Greenwich Park",
      description: "Large park with beautiful views and the Prime Meridian.",
      suggested_duration: "1hr - 2hr",
      tags: "nature,leisure,view",
      image: "Photo-11.jpg",
    },
    {
      location: "London",
      attraction_name: "The Shard",
      description: "Skyscraper with panoramic viewing platform.",
      suggested_duration: "1hr - 2hr",
      tags: "view,landmark,urban",
      image: "Photo-12.jpg",
    },

    // Tokyo (13-24)
    {
      location: "Tokyo",
      attraction_name: "Shibuya Crossing",
      description: "Famous busy pedestrian crossing.",
      suggested_duration: "1hr - 2hr",
      tags: "urban,landmark,iconic",
      image: "Photo-13.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Senso-ji Temple",
      description: "Historic Buddhist temple in Asakusa.",
      suggested_duration: "1hr - 2hr",
      tags: "temple,culture,history",
      image: "Photo-14.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tokyo Tower",
      description: "Eiffel Tower-inspired landmark with city views.",
      suggested_duration: "30min - 1hr",
      tags: "landmark,view,iconic",
      image: "Photo-15.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Akihabara",
      description: "Famous for electronics, anime, and gaming culture.",
      suggested_duration: "1hr - 2hr",
      tags: "anime,shopping,leisure",
      image: "Photo-16.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Shinjuku Gyoen",
      description: "Beautiful park with cherry blossoms in spring.",
      suggested_duration: "1hr - 3hr",
      tags: "park,nature,leisure",
      image: "Photo-17.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Meiji Shrine",
      description: "Shinto shrine dedicated to Emperor Meiji.",
      suggested_duration: "1hr - 2hr",
      tags: "shrine,culture,history",
      image: "Photo-18.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Odaiba",
      description: "Man-made island with shopping and entertainment.",
      suggested_duration: "2hr - 4hr",
      tags: "urban,shopping,leisure",
      image: "Photo-19.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tsukiji Outer Market",
      description: "Food market famous for fresh sushi.",
      suggested_duration: "1hr - 2hr",
      tags: "food,market,shopping",
      image: "Photo-20.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "TeamLab Planets",
      description: "Immersive digital art museum.",
      suggested_duration: "1hr - 2hr",
      tags: "art,culture,experience",
      image: "Photo-21.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Roppongi Hills",
      description: "Upscale area with shops and observation deck.",
      suggested_duration: "1hr - 2hr",
      tags: "shopping,view,leisure",
      image: "Photo-22.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tokyo Disneyland",
      description: "World-famous theme park for family fun.",
      suggested_duration: "4hr - 6hr",
      tags: "kids,family,leisure",
      image: "Photo-23.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Ueno Zoo",
      description: "Japan's oldest zoo with diverse animal exhibits.",
      suggested_duration: "2hr - 3hr",
      tags: "kids,nature,leisure",
      image: "Photo-24.jpg",
    },

    // Paris (25-34)
    {
      location: "Paris",
      attraction_name: "Eiffel Tower",
      description: "Iconic iron tower and symbol of Paris.",
      suggested_duration: "1hr - 2hr",
      tags: "landmark,view,iconic",
      image: "Photo-25.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Louvre Museum",
      description: "World's largest art museum, home to the Mona Lisa.",
      suggested_duration: "2hr - 4hr",
      tags: "museum,art,culture",
      image: "Photo-26.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Notre-Dame Cathedral",
      description: "Medieval Catholic cathedral with Gothic architecture.",
      suggested_duration: "1hr - 2hr",
      tags: "church,landmark,history",
      image: "Photo-27.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Montmartre",
      description: "Artistic hilltop district with the Sacré-Cœur Basilica.",
      suggested_duration: "2hr - 3hr",
      tags: "art,culture,view",
      image: "Photo-28.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Arc de Triomphe",
      description: "Iconic triumphal arch honoring those who fought for France.",
      suggested_duration: "30min - 1hr",
      tags: "landmark,history,architecture",
      image: "Photo-29.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Seine River Cruise",
      description: "Scenic boat tour along the Seine River.",
      suggested_duration: "1hr - 2hr",
      tags: "cruise,leisure,view",
      image: "Photo-30.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Musée d'Orsay",
      description: "Museum housed in a former railway station with impressionist art.",
      suggested_duration: "1hr - 3hr",
      tags: "museum,art,culture",
      image: "Photo-31.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Luxembourg Gardens",
      description: "Beautiful park with fountains, sculptures, and manicured lawns.",
      suggested_duration: "1hr - 2hr",
      tags: "park,nature,leisure",
      image: "Photo-32.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Centre Pompidou",
      description: "Modern and contemporary art museum with unique architecture.",
      suggested_duration: "1hr - 2hr",
      tags: "museum,art,architecture",
      image: "Photo-33.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Champs-Élysées",
      description: "Famous avenue known for luxury shops and cafes.",
      suggested_duration: "1hr - 3hr",
      tags: "shopping,urban,leisure",
      image: "Photo-34.jpg",
    },

    // Rome (35-44)
    {
      location: "Rome",
      attraction_name: "Colosseum",
      description: "Ancient amphitheater used for gladiatorial contests.",
      suggested_duration: "1hr - 2hr",
      tags: "landmark,history,architecture",
      image: "Photo-35.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Vatican Museums",
      description: "Art collections built up by the Popes, including the Sistine Chapel.",
      suggested_duration: "2hr - 3hr",
      tags: "museum,art,culture",
      image: "Photo-36.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Roman Forum",
      description: "Ruins of ancient government buildings at the center of Rome.",
      suggested_duration: "1hr - 2hr",
      tags: "ruins,history,landmark",
      image: "Photo-37.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Trevi Fountain",
      description: "Baroque fountain known for the coin-tossing tradition.",
      suggested_duration: "30min - 1hr",
      tags: "landmark,architecture,iconic",
      image: "Photo-38.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Pantheon",
      description: "Former Roman temple with a spectacular dome.",
      suggested_duration: "30min - 1hr",
      tags: "landmark,history,architecture",
      image: "Photo-39.jpg",
    },
    {
      location: "Rome",
      attraction_name: "St. Peter's Basilica",
      description: "One of the world's largest churches and center of Catholicism.",
      suggested_duration: "1hr - 2hr",
      tags: "church,architecture,landmark",
      image: "Photo-40.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Spanish Steps",
      description: "Monumental stairway connecting Piazza di Spagna and Trinità dei Monti church.",
      suggested_duration: "30min - 1hr",
      tags: "landmark,urban,leisure",
      image: "Photo-41.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Villa Borghese Gardens",
      description: "Large public park with museums and attractions.",
      suggested_duration: "1hr - 3hr",
      tags: "park,nature,leisure",
      image: "Photo-42.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Piazza Navona",
      description: "Public square with Baroque architecture and fountains.",
      suggested_duration: "30min - 1hr",
      tags: "urban,architecture,leisure",
      image: "Photo-43.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Palatine Hill",
      description: "One of the Seven Hills of Rome with ancient ruins.",
      suggested_duration: "1hr - 2hr",
      tags: "ruins,history,view",
      image: "Photo-44.jpg",
    },

    // Sydney (45-54)
    {
      location: "Sydney",
      attraction_name: "Sydney Opera House",
      description: "Iconic performing arts venue with distinctive sail-shaped design.",
      suggested_duration: "1hr - 2hr",
      tags: "landmark,architecture,culture",
      image: "Photo-45.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Sydney Harbour Bridge",
      description: "Steel arch bridge spanning Sydney Harbour.",
      suggested_duration: "1hr - 2hr",
      tags: "landmark,view,iconic",
      image: "Photo-46.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Bondi Beach",
      description: "Famous beach known for surfing and coastal walks.",
      suggested_duration: "2hr - 4hr",
      tags: "beach,nature,leisure",
      image: "Photo-47.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Taronga Zoo",
      description: "Zoo with Australian wildlife and spectacular harbour views.",
      suggested_duration: "2hr - 4hr",
      tags: "zoo,nature,family",
      image: "Photo-48.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Royal Botanic Garden",
      description: "Oasis of 30 hectares in the heart of the city.",
      suggested_duration: "1hr - 2hr",
      tags: "park,nature,leisure",
      image: "Photo-49.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Darling Harbour",
      description: "Recreational precinct with restaurants, museums, and shops.",
      suggested_duration: "2hr - 3hr",
      tags: "urban,leisure,shopping",
      image: "Photo-50.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "The Rocks",
      description: "Historic area with markets, pubs, and colonial buildings.",
      suggested_duration: "1hr - 2hr",
      tags: "history,shopping,urban",
      image: "Photo-51.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Queen Victoria Building",
      description: "Historic shopping center with Victorian architecture.",
      suggested_duration: "1hr - 2hr",
      tags: "shopping,architecture,history",
      image: "Photo-52.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Manly Beach",
      description: "Popular beach area accessible by scenic ferry ride.",
      suggested_duration: "2hr - 4hr",
      tags: "beach,nature,leisure",
      image: "Photo-53.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Blue Mountains",
      description: "Mountain range with dramatic scenery and hiking trails.",
      suggested_duration: "4hr - 8hr",
      tags: "nature,hiking,view",
      image: "Photo-54.jpg",
    },
  ]);
}
