/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex("attractions").del();
  await knex.raw("ALTER TABLE attractions AUTO_INCREMENT = 1");
  await knex("attractions").insert([
    // London (1-10)
    {
      location: "London",
      attraction_name: "Big Ben",
      description: "Iconic clock tower and landmark in London.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,history,culture",
      image: "Photo-1.jpg",
    },
    {
      location: "London",
      attraction_name: "Borough Market",
      description: "One of the oldest food market in London",
      suggested_duration: "1-2 hr",
      tags: "food,culture,leisure",
      image: "Photo-2.jpg",
    },
    {
      location: "London",
      attraction_name: "British Museum",
      description: "World-famous museum with historical artifacts.",
      suggested_duration: "1-2 hr",
      tags: "museum,culture,history",
      image: "Photo-3.jpg",
    },
    {
      location: "London",
      attraction_name: "London Eye",
      description: "Ferris wheel offering panoramic city views.",
      suggested_duration: "30min - 1 hr",
      tags: "view,landmark,leisure",
      image: "Photo-4.jpg",
    },
    {
      location: "London",
      attraction_name: "Hyde Park",
      description: "Large city park with walking paths and a lake.",
      suggested_duration: "1-3 hr",
      tags: "park,nature,leisure",
      image: "Photo-5.jpg",
    },
    {
      location: "London",
      attraction_name: "Buckingham Palace",
      description: "Official residence of the British monarch.",
      suggested_duration: "1-2 hr",
      tags: "royal,landmark,history",
      image: "Photo-6.jpg",
    },
    {
      location: "London",
      attraction_name: "Tower Bridge",
      description: "Iconic Victorian bridge over the River Thames with glass floor walkways and engine rooms.",
      suggested_duration: "1-2 hr",
      tags: "landmark,architecture,history",
      image: "Photo-7.jpg",
    },
    {
      location: "London",
      attraction_name: "Covent Garden",
      description: "Vibrant area with markets, shops, and street performers.",
      suggested_duration: "1-2 hr",
      tags: "market,shopping,leisure",
      image: "Photo-8.jpg",
    },
    {
      location: "London",
      attraction_name: "St. Paul's Cathedral",
      description: "Historic cathedral with a famous dome.",
      suggested_duration: "1-2 hr",
      tags: "church,landmark,architecture",
      image: "Photo-9.jpg",
    },
    {
      location: "London",
      attraction_name: "Camden Market",
      description: "Lively market known for food, fashion, and alternative culture.",
      suggested_duration: "1-2 hr",
      tags: "market,food,shopping",
      image: "Photo-10.jpg",
    },
    {
      location: "London",
      attraction_name: "Greenwich Park",
      description: "Large park with beautiful views and the Prime Meridian.",
      suggested_duration: "1-2 hr",
      tags: "nature,leisure,view",
      image: "Photo-11.jpg",
    },
    {
      location: "London",
      attraction_name: "The Shard",
      description: "Skyscraper with panoramic viewing platform.",
      suggested_duration: "1-2 hr",
      tags: "view,landmark,urban",
      image: "Photo-12.jpg",
    },

    // Tokyo (13-24)
    {
      location: "Tokyo",
      attraction_name: "Shibuya Crossing",
      description: "Famous busy pedestrian crossing.",
      suggested_duration: "1-2 hr",
      tags: "urban,landmark,iconic",
      image: "Photo-13.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Senso-ji Temple",
      description: "Historic Buddhist temple in Asakusa.",
      suggested_duration: "1-2 hr",
      tags: "temple,culture,history",
      image: "Photo-14.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tokyo Tower",
      description: "Eiffel Tower-inspired landmark with city views.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,view,iconic",
      image: "Photo-15.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Akihabara",
      description: "Famous for electronics, anime, and gaming culture.",
      suggested_duration: "1-2 hr",
      tags: "anime,shopping,leisure",
      image: "Photo-16.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Shinjuku Gyoen",
      description: "Beautiful park with cherry blossoms in spring.",
      suggested_duration: "1-3 hr",
      tags: "park,nature,leisure",
      image: "Photo-17.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Meiji Shrine",
      description: "Shinto shrine dedicated to Emperor Meiji.",
      suggested_duration: "1-2 hr",
      tags: "shrine,culture,history",
      image: "Photo-18.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Odaiba",
      description: "Man-made island with shopping and entertainment.",
      suggested_duration: "2-4 hr",
      tags: "urban,shopping,leisure",
      image: "Photo-19.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tsukiji Outer Market",
      description: "Food market famous for fresh sushi.",
      suggested_duration: "1-2 hr",
      tags: "food,market,shopping",
      image: "Photo-20.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "teamLab Planets TOKYO",
      description: "Immersive digital art museum with interactive installations.",
      suggested_duration: "1-2 hr",
      tags: "art,culture,experience",
      image: "Photo-21.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Roppongi Hills",
      description: "Upscale area with shops and observation deck.",
      suggested_duration: "1-2 hr",
      tags: "shopping,view,leisure",
      image: "Photo-22.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tokyo Disneyland",
      description: "World-famous theme park for family fun.",
      suggested_duration: "4-6 hr",
      tags: "kids,family,leisure",
      image: "Photo-23.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Ueno Zoo",
      description: "Japan's oldest zoo with diverse animal exhibits.",
      suggested_duration: "2-3 hr",
      tags: "kids,nature,leisure",
      image: "Photo-24.jpg",
    },

    // Paris (25-34)
    {
      location: "Paris",
      attraction_name: "Eiffel Tower",
      description: "Iconic iron tower and symbol of Paris.",
      suggested_duration: "1-2 hr",
      tags: "landmark,view,iconic",
      image: "Photo-25.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Louvre Museum",
      description: "World's largest art museum, home to the Mona Lisa.",
      suggested_duration: "2-4 hr",
      tags: "museum,art,culture",
      image: "Photo-26.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Notre-Dame Cathedral",
      description: "Medieval Catholic cathedral with Gothic architecture.",
      suggested_duration: "1-2 hr",
      tags: "church,landmark,history",
      image: "Photo-27.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Montmartre",
      description: "Artistic hilltop district with the Sacré-Cœur Basilica.",
      suggested_duration: "2-3 hr",
      tags: "art,culture,view",
      image: "Photo-28.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Arc de Triomphe",
      description: "Iconic triumphal arch honoring those who fought for France.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,history,architecture",
      image: "Photo-29.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Sainte-Chapelle",
      description: "Gothic chapel with spectacular stained glass windows.",
      suggested_duration: "1-2 hr",
      tags: "church,architecture,history",
      image: "Photo-30.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Musée d'Orsay",
      description: "Museum housed in a former railway station with impressionist art.",
      suggested_duration: "1-3 hr",
      tags: "museum,art,culture",
      image: "Photo-31.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Luxembourg Gardens",
      description: "Beautiful park with fountains, sculptures, and manicured lawns.",
      suggested_duration: "1-2 hr",
      tags: "park,nature,leisure",
      image: "Photo-32.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Centre Pompidou",
      description: "Modern and contemporary art museum with unique architecture.",
      suggested_duration: "1-2 hr",
      tags: "museum,art,architecture",
      image: "Photo-33.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Champs-Élysées",
      description: "Famous avenue known for luxury shops and cafes.",
      suggested_duration: "1-3 hr",
      tags: "shopping,urban,leisure",
      image: "Photo-34.jpg",
    },

    // Rome (35-44)
    {
      location: "Rome",
      attraction_name: "Colosseum",
      description: "Ancient amphitheater used for gladiatorial contests.",
      suggested_duration: "1-2 hr",
      tags: "landmark,history,architecture",
      image: "Photo-35.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Vatican Museums",
      description: "Art collections built up by the Popes, including the Sistine Chapel.",
      suggested_duration: "2-3 hr",
      tags: "museum,art,culture",
      image: "Photo-36.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Roman Forum",
      description: "Ruins of ancient government buildings at the center of Rome.",
      suggested_duration: "1-2 hr",
      tags: "ruins,history,landmark",
      image: "Photo-37.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Trevi Fountain",
      description: "Baroque fountain known for the coin-tossing tradition.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,architecture,iconic",
      image: "Photo-38.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Pantheon",
      description: "Former Roman temple with a spectacular dome.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,history,architecture",
      image: "Photo-39.jpg",
    },
    {
      location: "Rome",
      attraction_name: "St. Peter's Basilica",
      description: "One of the world's largest churches and center of Catholicism.",
      suggested_duration: "1-2 hr",
      tags: "church,architecture,landmark",
      image: "Photo-40.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Spanish Steps",
      description: "Monumental stairway connecting Piazza di Spagna and Trinità dei Monti church.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,urban,leisure",
      image: "Photo-41.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Villa Borghese Gardens",
      description: "Large public park with museums and attractions.",
      suggested_duration: "1-3 hr",
      tags: "park,nature,leisure",
      image: "Photo-42.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Piazza Navona",
      description: "Public square with Baroque architecture and fountains.",
      suggested_duration: "30min - 1 hr",
      tags: "urban,architecture,leisure",
      image: "Photo-43.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Palatine Hill",
      description: "One of the Seven Hills of Rome with ancient ruins.",
      suggested_duration: "1-2 hr",
      tags: "ruins,history,view",
      image: "Photo-44.jpg",
    },

    // Sydney (45-54)
    {
      location: "Sydney",
      attraction_name: "Sydney Opera House",
      description: "Iconic performing arts venue with distinctive sail-shaped design.",
      suggested_duration: "1-2 hr",
      tags: "landmark,architecture,culture",
      image: "Photo-45.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Sydney Harbour Bridge",
      description: "Steel arch bridge spanning Sydney Harbour.",
      suggested_duration: "1-2 hr",
      tags: "landmark,view,iconic",
      image: "Photo-46.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Bondi Beach",
      description: "Famous beach known for surfing and coastal walks.",
      suggested_duration: "2-4 hr",
      tags: "beach,nature,leisure",
      image: "Photo-47.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Taronga Zoo",
      description: "Zoo with Australian wildlife and spectacular harbour views.",
      suggested_duration: "2-4 hr",
      tags: "zoo,nature,family",
      image: "Photo-48.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Royal Botanic Garden",
      description: "Oasis of 30 hectares in the heart of the city.",
      suggested_duration: "1-2 hr",
      tags: "park,nature,leisure",
      image: "Photo-49.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Darling Harbour",
      description: "Recreational precinct with restaurants, museums, and shops.",
      suggested_duration: "2-3 hr",
      tags: "urban,leisure,shopping",
      image: "Photo-50.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "The Rocks",
      description: "Historic area with markets, pubs, and colonial buildings.",
      suggested_duration: "1-2 hr",
      tags: "history,shopping,urban",
      image: "Photo-51.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Queen Victoria Building",
      description: "Historic shopping center with Victorian architecture.",
      suggested_duration: "1-2 hr",
      tags: "shopping,architecture,history",
      image: "Photo-52.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Manly Beach",
      description: "Popular beach area accessible by scenic ferry ride.",
      suggested_duration: "2-4 hr",
      tags: "beach,nature,leisure",
      image: "Photo-53.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Luna Park Sydney",
      description: "Historic amusement park with rides, games and spectacular harbour views.",
      suggested_duration: "2-4 hr",
      tags: "amusement,family,leisure",
      image: "Photo-54.jpg",
    },

    // Barcelona (55-66)
    {
      location: "Barcelona",
      attraction_name: "Sagrada Familia",
      description: "Iconic basilica designed by Antoni Gaudí, still under construction.",
      suggested_duration: "1-3 hr",
      tags: "landmark,architecture,church",
      image: "Photo-55.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Park Güell",
      description: "Public park with Gaudí's colorful mosaics and architectural elements.",
      suggested_duration: "1-2 hr",
      tags: "park,architecture,view",
      image: "Photo-56.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Casa Vicens",
      description: "First house designed by Antoni Gaudí, featuring Moorish influences and colorful ceramic tiles.",
      suggested_duration: "1-2 hr",
      tags: "architecture,history,culture",
      image: "Photo-57.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Barri Gòtic (Gothic Quarter)",
      description: "Historic center with narrow medieval streets and picturesque squares.",
      suggested_duration: "2-3 hr",
      tags: "history,urban,architecture",
      image: "Photo-58.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Casa Batlló",
      description: "Modernist building designed by Antoni Gaudí with unique facade.",
      suggested_duration: "1-2 hr",
      tags: "architecture,culture,landmark",
      image: "Photo-59.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "La Boqueria Market",
      description: "Famous public market with fresh produce, meat, and seafood.",
      suggested_duration: "1-2 hr",
      tags: "food,market,shopping",
      image: "Photo-60.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Barceloneta Beach",
      description: "Popular city beach with promenade and seafood restaurants.",
      suggested_duration: "2-4 hr",
      tags: "beach,leisure,urban",
      image: "Photo-61.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Montjuïc",
      description: "Hill with parks, gardens, and the Olympic stadium.",
      suggested_duration: "2-4 hr",
      tags: "nature,view,history",
      image: "Photo-62.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Picasso Museum",
      description: "Museum dedicated to Pablo Picasso's works, housed in medieval palaces.",
      suggested_duration: "1-2 hr",
      tags: "museum,art,culture",
      image: "Photo-63.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Camp Nou",
      description: "FC Barcelona's football stadium, one of the largest in Europe.",
      suggested_duration: "1-2 hr",
      tags: "sports,landmark,urban",
      image: "Photo-64.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Palau de la Música Catalana",
      description: "Modernist concert hall with stunning stained glass and sculptures.",
      suggested_duration: "1-2 hr",
      tags: "architecture,music,culture",
      image: "Photo-65.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Casa Milà (La Pedrera)",
      description: "Gaudí-designed apartment building with undulating facade and rooftop.",
      suggested_duration: "1-2 hr",
      tags: "architecture,landmark,culture",
      image: "Photo-66.jpg",
    },

    // Bangkok
    {
      location: "Bangkok",
      attraction_name: "Grand Palace",
      description: "Historic royal residence with ornate architecture and the sacred Emerald Buddha.",
      suggested_duration: "2-3 hr",
      tags: "landmark,culture,history",
      image: "Photo-67.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "Wat Arun",
      description: "Iconic riverside temple with a striking prang (spire) decorated with colorful porcelain.",
      suggested_duration: "1-2 hr",
      tags: "temple,landmark,architecture",
      image: "Photo-68.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "Chatuchak Weekend Market",
      description: "One of the world's largest weekend markets with over 15,000 stalls.",
      suggested_duration: "2-4 hr",
      tags: "shopping,market,food",
      image: "Photo-69.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "Wat Pho",
      description: "Temple of the Reclining Buddha, home to one of Thailand's largest Buddha statues.",
      suggested_duration: "1-2 hr",
      tags: "temple,culture,landmark",
      image: "Photo-70.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "Jim Thompson House",
      description: "Museum housing the art collection of American businessman Jim Thompson in traditional Thai houses.",
      suggested_duration: "1-2 hr",
      tags: "museum,culture,architecture",
      image: "Photo-71.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "Chinatown Bangkok",
      description: "Bustling district with narrow alleys, street food vendors, and gold shops.",
      suggested_duration: "2-3 hr",
      tags: "food,culture,shopping",
      image: "Photo-72.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "Lumphini Park",
      description: "Urban oasis with a lake, walking paths, and monitor lizards.",
      suggested_duration: "1-2 hr",
      tags: "park,nature,leisure",
      image: "Photo-73.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "MBK Center",
      description: "Popular shopping mall known for electronics, clothing, and souvenirs at bargain prices.",
      suggested_duration: "2-3 hr",
      tags: "shopping,urban,leisure",
      image: "Photo-74.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "Khaosan Road",
      description: "Famous backpacker street with shops, bars, restaurants, and street food.",
      suggested_duration: "1-2 hr",
      tags: "nightlife,food,shopping",
      image: "Photo-75.jpg",
    },
    {
      location: "Bangkok",
      attraction_name: "Asiatique The Riverfront",
      description: "Night market and mall with riverside dining, shopping, and entertainment.",
      suggested_duration: "2-3 hr",
      tags: "shopping,food,nightlife",
      image: "Photo-76.jpg",
    },
    // Miami (77-88)
    {
      location: "Miami",
      attraction_name: "South Beach",
      description: "Famous beach known for its white sand, clear water, and vibrant nightlife.",
      suggested_duration: "2-4 hr",
      tags: "beach,leisure,nightlife",
      image: "Photo-77.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Wynwood Walls",
      description: "Outdoor museum showcasing large-scale works by street artists.",
      suggested_duration: "1-2 hr",
      tags: "art,culture,urban",
      image: "Photo-78.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Vizcaya Museum and Gardens",
      description: "Historic mansion with stunning European-inspired gardens.",
      suggested_duration: "1-2 hr",
      tags: "museum,garden,history",
      image: "Photo-79.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Little Havana",
      description: "Cuban cultural district with food, music, and street art.",
      suggested_duration: "1-2 hr",
      tags: "culture,food,urban",
      image: "Photo-80.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Miami Design District",
      description: "Trendy area with high-end shops, galleries, and architecture.",
      suggested_duration: "1-2 hr",
      tags: "shopping,art,leisure",
      image: "Photo-81.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Everglades National Park",
      description: "Unique wetlands with wildlife viewing and airboat tours.",
      suggested_duration: "2-4 hr",
      tags: "nature,adventure,wildlife",
      image: "Photo-82.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Bayfront Park",
      description: "Waterfront green space with trails and event venues.",
      suggested_duration: "1-2 hr",
      tags: "park,leisure,urban",
      image: "Photo-83.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Perez Art Museum Miami (PAMM)",
      description: "Modern and contemporary art museum with waterfront views.",
      suggested_duration: "1-2 hr",
      tags: "museum,art,culture",
      image: "Photo-84.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Crandon Park Beach",
      description: "Family-friendly beach with calm waters and picnic areas.",
      suggested_duration: "2-4 hr",
      tags: "beach,leisure,family",
      image: "Photo-85.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Jungle Island",
      description: "Interactive zoological park with exotic animals.",
      suggested_duration: "2-3 hr",
      tags: "nature,animals,family",
      image: "Photo-86.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Phillip and Patricia Frost Museum of Science",
      description: "Science museum with planetarium and aquarium.",
      suggested_duration: "2-3 hr",
      tags: "museum,science,family",
      image: "Photo-87.jpg",
    },
    {
      location: "Miami",
      attraction_name: "Bill Baggs Cape Florida State Park",
      description: "Beautiful beach and historic lighthouse with walking trails.",
      suggested_duration: "2-3 hr",
      tags: "nature,beach,leisure",
      image: "Photo-88.jpg",
    },
  ]);
}
