/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex("attractions").del();
  await knex.raw("ALTER TABLE attractions AUTO_INCREMENT = 1");
  await knex("attractions").insert([
    // London (1-10)
    {
      location: "London",
      attraction_name: "Big Ben",
      description: "Iconic clock tower and landmark in London.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,history,culture",
      image: "Photo-1.jpg",
    },
    {
      location: "London",
      attraction_name: "Borough Market",
      description: "One of the oldest food market in London",
      suggested_duration: "1-2 hr",
      tags: "food,culture,leisure",
      image: "Photo-2.jpg",
    },
    {
      location: "London",
      attraction_name: "British Museum",
      description: "World-famous museum with historical artifacts.",
      suggested_duration: "1-2 hr",
      tags: "museum,culture,history",
      image: "Photo-3.jpg",
    },
    {
      location: "London",
      attraction_name: "London Eye",
      description: "Ferris wheel offering panoramic city views.",
      suggested_duration: "30min - 1 hr",
      tags: "view,landmark,leisure",
      image: "Photo-4.jpg",
    },
    {
      location: "London",
      attraction_name: "Hyde Park",
      description: "Large city park with walking paths and a lake.",
      suggested_duration: "1-3 hr",
      tags: "park,nature,leisure",
      image: "Photo-5.jpg",
    },
    {
      location: "London",
      attraction_name: "Buckingham Palace",
      description: "Official residence of the British monarch.",
      suggested_duration: "1-2 hr",
      tags: "royal,landmark,history",
      image: "Photo-6.jpg",
    },
    {
      location: "London",
      attraction_name: "Tate Modern",
      description: "Modern art gallery housed in a former power station.",
      suggested_duration: "1-2 hr",
      tags: "museum,art,culture",
      image: "Photo-7.jpg",
    },
    {
      location: "London",
      attraction_name: "Covent Garden",
      description: "Vibrant area with markets, shops, and street performers.",
      suggested_duration: "1-2 hr",
      tags: "market,shopping,leisure",
      image: "Photo-8.jpg",
    },
    {
      location: "London",
      attraction_name: "St. Paul's Cathedral",
      description: "Historic cathedral with a famous dome.",
      suggested_duration: "1-2 hr",
      tags: "church,landmark,architecture",
      image: "Photo-9.jpg",
    },
    {
      location: "London",
      attraction_name: "Camden Market",
      description: "Lively market known for food, fashion, and alternative culture.",
      suggested_duration: "1-2 hr",
      tags: "market,food,shopping",
      image: "Photo-10.jpg",
    },
    {
      location: "London",
      attraction_name: "Greenwich Park",
      description: "Large park with beautiful views and the Prime Meridian.",
      suggested_duration: "1-2 hr",
      tags: "nature,leisure,view",
      image: "Photo-11.jpg",
    },
    {
      location: "London",
      attraction_name: "The Shard",
      description: "Skyscraper with panoramic viewing platform.",
      suggested_duration: "1-2 hr",
      tags: "view,landmark,urban",
      image: "Photo-12.jpg",
    },

    // Tokyo (13-24)
    {
      location: "Tokyo",
      attraction_name: "Shibuya Crossing",
      description: "Famous busy pedestrian crossing.",
      suggested_duration: "1-2 hr",
      tags: "urban,landmark,iconic",
      image: "Photo-13.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Senso-ji Temple",
      description: "Historic Buddhist temple in Asakusa.",
      suggested_duration: "1-2 hr",
      tags: "temple,culture,history",
      image: "Photo-14.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tokyo Tower",
      description: "Eiffel Tower-inspired landmark with city views.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,view,iconic",
      image: "Photo-15.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Akihabara",
      description: "Famous for electronics, anime, and gaming culture.",
      suggested_duration: "1-2 hr",
      tags: "anime,shopping,leisure",
      image: "Photo-16.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Shinjuku Gyoen",
      description: "Beautiful park with cherry blossoms in spring.",
      suggested_duration: "1-3 hr",
      tags: "park,nature,leisure",
      image: "Photo-17.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Meiji Shrine",
      description: "Shinto shrine dedicated to Emperor Meiji.",
      suggested_duration: "1-2 hr",
      tags: "shrine,culture,history",
      image: "Photo-18.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Odaiba",
      description: "Man-made island with shopping and entertainment.",
      suggested_duration: "2-4 hr",
      tags: "urban,shopping,leisure",
      image: "Photo-19.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tsukiji Outer Market",
      description: "Food market famous for fresh sushi.",
      suggested_duration: "1-2 hr",
      tags: "food,market,shopping",
      image: "Photo-20.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "teamLab Planets TOKYO",
      description: "Immersive digital art museum with interactive installations.",
      suggested_duration: "1-2 hr",
      tags: "art,culture,experience",
      image: "Photo-21.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Roppongi Hills",
      description: "Upscale area with shops and observation deck.",
      suggested_duration: "1-2 hr",
      tags: "shopping,view,leisure",
      image: "Photo-22.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Tokyo Disneyland",
      description: "World-famous theme park for family fun.",
      suggested_duration: "4-6 hr",
      tags: "kids,family,leisure",
      image: "Photo-23.jpg",
    },
    {
      location: "Tokyo",
      attraction_name: "Ueno Zoo",
      description: "Japan's oldest zoo with diverse animal exhibits.",
      suggested_duration: "2-3 hr",
      tags: "kids,nature,leisure",
      image: "Photo-24.jpg",
    },

    // Paris (25-34)
    {
      location: "Paris",
      attraction_name: "Eiffel Tower",
      description: "Iconic iron tower and symbol of Paris.",
      suggested_duration: "1-2 hr",
      tags: "landmark,view,iconic",
      image: "Photo-25.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Louvre Museum",
      description: "World's largest art museum, home to the Mona Lisa.",
      suggested_duration: "2-4 hr",
      tags: "museum,art,culture",
      image: "Photo-26.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Notre-Dame Cathedral",
      description: "Medieval Catholic cathedral with Gothic architecture.",
      suggested_duration: "1-2 hr",
      tags: "church,landmark,history",
      image: "Photo-27.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Montmartre",
      description: "Artistic hilltop district with the Sacré-Cœur Basilica.",
      suggested_duration: "2-3 hr",
      tags: "art,culture,view",
      image: "Photo-28.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Arc de Triomphe",
      description: "Iconic triumphal arch honoring those who fought for France.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,history,architecture",
      image: "Photo-29.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Sainte-Chapelle",
      description: "Gothic chapel with spectacular stained glass windows.",
      suggested_duration: "1-2 hr",
      tags: "church,architecture,history",
      image: "Photo-30.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Musée d'Orsay",
      description: "Museum housed in a former railway station with impressionist art.",
      suggested_duration: "1-3 hr",
      tags: "museum,art,culture",
      image: "Photo-31.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Luxembourg Gardens",
      description: "Beautiful park with fountains, sculptures, and manicured lawns.",
      suggested_duration: "1-2 hr",
      tags: "park,nature,leisure",
      image: "Photo-32.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Centre Pompidou",
      description: "Modern and contemporary art museum with unique architecture.",
      suggested_duration: "1-2 hr",
      tags: "museum,art,architecture",
      image: "Photo-33.jpg",
    },
    {
      location: "Paris",
      attraction_name: "Champs-Élysées",
      description: "Famous avenue known for luxury shops and cafes.",
      suggested_duration: "1-3 hr",
      tags: "shopping,urban,leisure",
      image: "Photo-34.jpg",
    },

    // Rome (35-44)
    {
      location: "Rome",
      attraction_name: "Colosseum",
      description: "Ancient amphitheater used for gladiatorial contests.",
      suggested_duration: "1-2 hr",
      tags: "landmark,history,architecture",
      image: "Photo-35.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Vatican Museums",
      description: "Art collections built up by the Popes, including the Sistine Chapel.",
      suggested_duration: "2-3 hr",
      tags: "museum,art,culture",
      image: "Photo-36.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Roman Forum",
      description: "Ruins of ancient government buildings at the center of Rome.",
      suggested_duration: "1-2 hr",
      tags: "ruins,history,landmark",
      image: "Photo-37.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Trevi Fountain",
      description: "Baroque fountain known for the coin-tossing tradition.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,architecture,iconic",
      image: "Photo-38.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Pantheon",
      description: "Former Roman temple with a spectacular dome.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,history,architecture",
      image: "Photo-39.jpg",
    },
    {
      location: "Rome",
      attraction_name: "St. Peter's Basilica",
      description: "One of the world's largest churches and center of Catholicism.",
      suggested_duration: "1-2 hr",
      tags: "church,architecture,landmark",
      image: "Photo-40.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Spanish Steps",
      description: "Monumental stairway connecting Piazza di Spagna and Trinità dei Monti church.",
      suggested_duration: "30min - 1 hr",
      tags: "landmark,urban,leisure",
      image: "Photo-41.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Villa Borghese Gardens",
      description: "Large public park with museums and attractions.",
      suggested_duration: "1-3 hr",
      tags: "park,nature,leisure",
      image: "Photo-42.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Piazza Navona",
      description: "Public square with Baroque architecture and fountains.",
      suggested_duration: "30min - 1 hr",
      tags: "urban,architecture,leisure",
      image: "Photo-43.jpg",
    },
    {
      location: "Rome",
      attraction_name: "Palatine Hill",
      description: "One of the Seven Hills of Rome with ancient ruins.",
      suggested_duration: "1-2 hr",
      tags: "ruins,history,view",
      image: "Photo-44.jpg",
    },

    // Sydney (45-54)
    {
      location: "Sydney",
      attraction_name: "Sydney Opera House",
      description: "Iconic performing arts venue with distinctive sail-shaped design.",
      suggested_duration: "1-2 hr",
      tags: "landmark,architecture,culture",
      image: "Photo-45.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Sydney Harbour Bridge",
      description: "Steel arch bridge spanning Sydney Harbour.",
      suggested_duration: "1-2 hr",
      tags: "landmark,view,iconic",
      image: "Photo-46.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Bondi Beach",
      description: "Famous beach known for surfing and coastal walks.",
      suggested_duration: "2-4 hr",
      tags: "beach,nature,leisure",
      image: "Photo-47.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Taronga Zoo",
      description: "Zoo with Australian wildlife and spectacular harbour views.",
      suggested_duration: "2-4 hr",
      tags: "zoo,nature,family",
      image: "Photo-48.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Royal Botanic Garden",
      description: "Oasis of 30 hectares in the heart of the city.",
      suggested_duration: "1-2 hr",
      tags: "park,nature,leisure",
      image: "Photo-49.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Darling Harbour",
      description: "Recreational precinct with restaurants, museums, and shops.",
      suggested_duration: "2-3 hr",
      tags: "urban,leisure,shopping",
      image: "Photo-50.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "The Rocks",
      description: "Historic area with markets, pubs, and colonial buildings.",
      suggested_duration: "1-2 hr",
      tags: "history,shopping,urban",
      image: "Photo-51.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Queen Victoria Building",
      description: "Historic shopping center with Victorian architecture.",
      suggested_duration: "1-2 hr",
      tags: "shopping,architecture,history",
      image: "Photo-52.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Manly Beach",
      description: "Popular beach area accessible by scenic ferry ride.",
      suggested_duration: "2-4 hr",
      tags: "beach,nature,leisure",
      image: "Photo-53.jpg",
    },
    {
      location: "Sydney",
      attraction_name: "Blue Mountains National Park",
      description: "Protected national park with dramatic scenery, hiking trails and the Three Sisters rock formation.",
      suggested_duration: "4-8 hr",
      tags: "nature,hiking,view",
      image: "Photo-54.jpg",
    },

    // Barcelona (55-66)
    {
      location: "Barcelona",
      attraction_name: "Sagrada Familia",
      description: "Iconic basilica designed by Antoni Gaudí, still under construction.",
      suggested_duration: "1-3 hr",
      tags: "landmark,architecture,church",
      image: "Photo-55.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Park Güell",
      description: "Public park with Gaudí's colorful mosaics and architectural elements.",
      suggested_duration: "1-2 hr",
      tags: "park,architecture,view",
      image: "Photo-56.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "La Rambla",
      description: "Famous tree-lined pedestrian street with shops and cafes.",
      suggested_duration: "1-2 hr",
      tags: "urban,shopping,leisure",
      image: "Photo-57.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Barri Gòtic (Gothic Quarter)",
      description: "Historic center with narrow medieval streets and picturesque squares.",
      suggested_duration: "2-3 hr",
      tags: "history,urban,architecture",
      image: "Photo-58.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Casa Batlló",
      description: "Modernist building designed by Antoni Gaudí with unique facade.",
      suggested_duration: "1-2 hr",
      tags: "architecture,culture,landmark",
      image: "Photo-59.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "La Boqueria Market",
      description: "Famous public market with fresh produce, meat, and seafood.",
      suggested_duration: "1-2 hr",
      tags: "food,market,shopping",
      image: "Photo-60.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Barceloneta Beach",
      description: "Popular city beach with promenade and seafood restaurants.",
      suggested_duration: "2-4 hr",
      tags: "beach,leisure,urban",
      image: "Photo-61.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Montjuïc",
      description: "Hill with parks, gardens, and the Olympic stadium.",
      suggested_duration: "2-4 hr",
      tags: "nature,view,history",
      image: "Photo-62.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Picasso Museum",
      description: "Museum dedicated to Pablo Picasso's works, housed in medieval palaces.",
      suggested_duration: "1-2 hr",
      tags: "museum,art,culture",
      image: "Photo-63.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Camp Nou",
      description: "FC Barcelona's football stadium, one of the largest in Europe.",
      suggested_duration: "1-2 hr",
      tags: "sports,landmark,urban",
      image: "Photo-64.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Palau de la Música Catalana",
      description: "Modernist concert hall with stunning stained glass and sculptures.",
      suggested_duration: "1-2 hr",
      tags: "architecture,music,culture",
      image: "Photo-65.jpg",
    },
    {
      location: "Barcelona",
      attraction_name: "Casa Milà (La Pedrera)",
      description: "Gaudí-designed apartment building with undulating facade and rooftop.",
      suggested_duration: "1-2 hr",
      tags: "architecture,landmark,culture",
      image: "Photo-66.jpg",
    },

    // Marrakech (67-76)
    {
      location: "Marrakech",
      attraction_name: "Jemaa el-Fnaa",
      description: "Famous main square and marketplace with food stalls, performers, and vendors.",
      suggested_duration: "1-3 hr",
      tags: "market,culture,food",
      image: "Photo-67.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "Jardin Majorelle",
      description: "Botanical garden with vibrant blue buildings, exotic plants, and Berber Museum.",
      suggested_duration: "1-2 hr",
      tags: "garden,art,culture",
      image: "Photo-68.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "Bahia Palace",
      description: "19th-century palace with beautiful courtyards, gardens and Moroccan architecture.",
      suggested_duration: "1-2 hr",
      tags: "palace,history,architecture",
      image: "Photo-69.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "Koutoubia Mosque",
      description: "Largest mosque in Marrakech with iconic minaret visible throughout the city.",
      suggested_duration: "30min - 1 hr",
      tags: "mosque,landmark,architecture",
      image: "Photo-70.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "Saadian Tombs",
      description: "Historic royal necropolis with ornate decorations and mausoleums.",
      suggested_duration: "1-2 hr",
      tags: "history,architecture,landmark",
      image: "Photo-71.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "Medina of Marrakech",
      description: "UNESCO-listed historic old city with narrow streets, souks, and traditional houses.",
      suggested_duration: "2-4 hr",
      tags: "shopping,history,culture",
      image: "Photo-72.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "El Badi Palace",
      description: "Ruins of a once-magnificent palace with sunken gardens and pavilions.",
      suggested_duration: "1-2 hr",
      tags: "ruins,history,architecture",
      image: "Photo-73.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "Musée Yves Saint Laurent Marrakech",
      description: "Contemporary museum dedicated to the fashion designer with rotating exhibitions.",
      suggested_duration: "1-2 hr",
      tags: "museum,fashion,culture",
      image: "Photo-74.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "Ben Youssef Madrasa",
      description: "Former Islamic college with stunning courtyards and intricate mosaics.",
      suggested_duration: "1-2 hr",
      tags: "history,architecture,culture",
      image: "Photo-75.jpg",
    },
    {
      location: "Marrakech",
      attraction_name: "Le Jardin Secret",
      description: "Restored historic palace with Islamic gardens and traditional water features.",
      suggested_duration: "1-2 hr",
      tags: "garden,history,architecture",
      image: "Photo-76.jpg",
    },
  ]);
}
